# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\"_\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12 \n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x0e.MovieCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"@\n\x13MovieRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\"G\n\x16RecommendationResponse\x12-\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x14.MovieRecommendation*]\n\rMovieCategory\x12\n\n\x06\x41\x63tion\x10\x00\x12\r\n\tAdventure\x10\x01\x12\n\n\x06\x43omedy\x10\x02\x12\n\n\x06Horror\x10\x03\x12\x0c\n\x08Thriller\x10\x04\x12\x0b\n\x07\x46\x61ntasy\x10\x05\x32O\n\x0fRecommendations\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponseb\x06proto3')

_MOVIECATEGORY = DESCRIPTOR.enum_types_by_name['MovieCategory']
MovieCategory = enum_type_wrapper.EnumTypeWrapper(_MOVIECATEGORY)
Action = 0
Adventure = 1
Comedy = 2
Horror = 3
Thriller = 4
Fantasy = 5


_RECOMMENDATIONREQUEST = DESCRIPTOR.message_types_by_name['RecommendationRequest']
_MOVIERECOMMENDATION = DESCRIPTOR.message_types_by_name['MovieRecommendation']
_RECOMMENDATIONRESPONSE = DESCRIPTOR.message_types_by_name['RecommendationResponse']
RecommendationRequest = _reflection.GeneratedProtocolMessageType('RecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONREQUEST,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationRequest)
  })
_sym_db.RegisterMessage(RecommendationRequest)

MovieRecommendation = _reflection.GeneratedProtocolMessageType('MovieRecommendation', (_message.Message,), {
  'DESCRIPTOR' : _MOVIERECOMMENDATION,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:MovieRecommendation)
  })
_sym_db.RegisterMessage(MovieRecommendation)

RecommendationResponse = _reflection.GeneratedProtocolMessageType('RecommendationResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONRESPONSE,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationResponse)
  })
_sym_db.RegisterMessage(RecommendationResponse)

_RECOMMENDATIONS = DESCRIPTOR.services_by_name['Recommendations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIECATEGORY._serialized_start=261
  _MOVIECATEGORY._serialized_end=354
  _RECOMMENDATIONREQUEST._serialized_start=25
  _RECOMMENDATIONREQUEST._serialized_end=120
  _MOVIERECOMMENDATION._serialized_start=122
  _MOVIERECOMMENDATION._serialized_end=186
  _RECOMMENDATIONRESPONSE._serialized_start=188
  _RECOMMENDATIONRESPONSE._serialized_end=259
  _RECOMMENDATIONS._serialized_start=356
  _RECOMMENDATIONS._serialized_end=435
# @@protoc_insertion_point(module_scope)
